In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [ ]:
docs = ['너무 재밌네요',
        '최고에요',
        '참 잘 만든 영화에요',
        '추천하고 싶은 영화입니다',
        '한번 더 보고싶네요',
        '글쎄요',
        '별로에요',
        '생각보다 지루하네요',
        '연기가 어색해요',
        '재미없어요']

In [ ]:
classes = array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [ ]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과 : \n", x)


리뷰 텍스트, 토큰화 결과 : 
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [ ]:
# 패딩, 길이가 다른 데이터를 4로 맞추기
padded_x = pad_sequences(x,4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [ ]:
# 단어 임베딩
word_size = len(token.word_index) + 1
word_size

21

In [ ]:
# 단어 임베딩을 포함해 딥러닝 모델
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics =['accuracy'])

In [ ]:
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 16ms/step - loss: 0.6575 - accuracy: 0.8000
Epoch 2/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6557 - accuracy: 0.9000
Epoch 3/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6539 - accuracy: 0.9000
Epoch 4/20
1/1 [==============================] - 0s 21ms/step - loss: 0.6521 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6503 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6485 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6466 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6448 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6429 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6410 - accuracy: 0.9000
Epoch 11/20
1/1 [==============

In [ ]:
print('\n Accuracy: {:.4f}'.format(model.evaluate(padded_x , classes)[1]))

1/1 [==============================] - 0s 28ms/step - loss: 0.6187 - accuracy: 0.9000

 Accuracy: 0.9000
