In [55]:
import numpy as np

In [36]:
arr1 = np.arange(4).reshape(1,4)
arr2 = np.arange(8).reshape(2,4)
arr3 = np.arange(4,8).reshape(1,4)

In [37]:
arr1, arr2, arr3

(array([[0, 1, 2, 3]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[4, 5, 6, 7]]))

In [38]:
np.concatenate([arr1, arr2], axis=0)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
np.concatenate([arr1,arr3], axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [23]:
a = np.arange(4)

In [31]:
arr1.ndim


2

In [42]:
a = np.random.randint(1,10, size=4)


In [43]:
a

array([4, 7, 3, 1])

In [49]:
a = a.reshape(2,2)

In [52]:
a/10

array([[0.4, 0.7],
       [0.3, 0.1]])

In [58]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)

In [59]:
a, b

(array([[1, 2],
        [3, 4]]),
 array([[6, 7],
        [8, 9]]))

In [60]:
a+b

array([[ 7,  9],
       [11, 13]])

In [61]:
a*b

array([[ 6, 14],
       [24, 36]])

In [63]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
arr1 = np.arange(0,8).reshape(2,4)
arr2 = np.arange(0,8).reshape(2,4)
arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [65]:
arr4 = np.arange(0,4).reshape(4,1)

In [66]:
arr4

array([[0],
       [1],
       [2],
       [3]])

In [67]:
arr3+arr4

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [70]:
arr1 = np.arange(16).reshape(4,4)
arr2 = arr1 <10
print(arr1, arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [72]:
arr1[arr2] = 100

In [73]:
arr1

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100,  10,  11],
       [ 12,  13,  14,  15]])

In [74]:
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [75]:
np.sum(arr, axis=0)

array([24, 28, 32, 36])

In [76]:
np.sum(arr, axis=1)

array([ 6, 22, 38, 54])

# 문제 풀이

In [ ]:
import numpy as np

In [77]:
#1. Create a null vector of size 10 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
#2.
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [80]:
#3.
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [84]:
#4. 
X = np.arange(10,50)
print(X)
print(X[::-1])
print(np.flip(X))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [85]:
#5. 
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
#6.
f = np.array([1,2,0,0,4,0])

a = -1
for i in f:
    a +=1
    if i !=0:
        print(a)

0
1
4


In [90]:
#6. 다른 풀이
print(np.where(f>0))
print(np.nonzero(f))

(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


In [99]:
#7
print(np.random.random(27).reshape(3,3,3))
print('\n')
print(np.random.random((3,3,3)))

[[[0.7355894  0.69478829 0.34550341]
  [0.56128872 0.39981155 0.04696427]
  [0.88580061 0.38340366 0.383897  ]]

 [[0.69320931 0.58011768 0.7244867 ]
  [0.95661009 0.23468064 0.78829981]
  [0.42936601 0.97503006 0.73494434]]

 [[0.59399329 0.5745161  0.70965988]
  [0.40109623 0.20026862 0.47244685]
  [0.50897106 0.93625741 0.80790641]]]


[[[0.61329782 0.33354971 0.81026874]
  [0.56902736 0.20864499 0.74158367]
  [0.19600623 0.97311294 0.65157242]]

 [[0.74151714 0.04923975 0.91564821]
  [0.22970869 0.79586197 0.69199805]
  [0.34193538 0.90802387 0.69602557]]

 [[0.56155603 0.70651443 0.17927532]
  [0.03675674 0.92499436 0.64238144]
  [0.47278494 0.68589169 0.38436027]]]


In [106]:
# 8.
a = np.random.randint(1,10,size=100).reshape(10,10)
a.max(), a.min()

(9, 1)

In [107]:
#9.
a = np.random.random(size=30)
a.mean()

0.5367388915293059

In [115]:
#10.
arr = np.ones((3,5))
print(arr)
print('\n')
arr[1,1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [119]:
#11
z = np.ones((5,5))
np.pad(z, pad_width=1, mode='constant', constant_values=0)


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [154]:
#12.
b = np.arange(11)
print(b)
b[(b>=3) & (b<=8)] *= -1
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [160]:
#13. 
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print(a2)
set(a1) & set(a2)

[7 4 5 4 8 1 9 8 6 5]
[4 8 5 6 0 7 6 3 4 2]


{4, 5, 6, 7, 8}

In [161]:
#13. 
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print(a2)
np.intersect1d(a1,a2)

[8 8 0 4 2 6 6 6 4 8]
[4 3 3 7 9 0 2 5 7 2]


array([0, 2, 4])

In [166]:
#14.
z = np.zeros((5,5))
print(z)
t = np.arange(5)
print(t)
z+t

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [176]:
#15.
z = np.random.random(size=10)
print(z)
z.sort()
print(z)

[0.92071605 0.28517596 0.4359523  0.83311144 0.54172405 0.73569811
 0.02049264 0.6124031  0.19876272 0.47987651]
[0.02049264 0.19876272 0.28517596 0.4359523  0.47987651 0.54172405
 0.6124031  0.73569811 0.83311144 0.92071605]


In [179]:
#16.
a = np.arange(10)
print(a.sum())
print(np.add.reduce(a))

45
45


In [212]:
#17.

a = np.random.randint(0,2,2)
b = np.random.randint(0,2,2)
print(a,b)
print(np.allclose(a,b))
print(np.array_equal(a,b))

[0 0] [0 0]
True
True


In [232]:
# 18.
num = 7.3
z = np.random.randint(0,10,10)

i = np.abs(num-z).argmin()
print('값은', z[i], '위치는', i)

값은 7 위치는 9


In [235]:
a = np.arange(25).reshape(5,5)
print(a,'\n')
a[[0,1]] = a[[1,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [238]:
a[[0,2]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])