# 폐암 수술 환자의 생존율 예측 - 딥러닝

1. 환경준비

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [2]:
# git에 있는 데이터 가져오기
!git clone https://github.com/taehojo/data.git

Cloning into 'data'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 3), reused 20 (delta 2), pack-reused 0
Unpacking objects: 100% (21/21), done.


2. 데이터 준비

In [3]:
Data_set = np.loadtxt("/content/data/ThoraricSurgery3.csv", delimiter=',')

Data_set

array([[ 1.  ,  2.88,  2.16, ...,  0.  , 60.  ,  0.  ],
       [ 2.  ,  3.4 ,  1.88, ...,  0.  , 51.  ,  0.  ],
       [ 2.  ,  2.76,  2.08, ...,  0.  , 59.  ,  0.  ],
       ...,
       [ 2.  ,  3.04,  2.08, ...,  0.  , 52.  ,  0.  ],
       [ 2.  ,  1.96,  1.68, ...,  0.  , 79.  ,  0.  ],
       [ 2.  ,  4.72,  3.56, ...,  0.  , 51.  ,  0.  ]])

In [4]:
X = Data_set[:,:-1]
y = Data_set[:,-1] # -1대신 16으로 해도 됨(16열까지 있음ㅁ)

In [5]:
X, y

(array([[ 1.  ,  2.88,  2.16, ...,  1.  ,  0.  , 60.  ],
        [ 2.  ,  3.4 ,  1.88, ...,  1.  ,  0.  , 51.  ],
        [ 2.  ,  2.76,  2.08, ...,  1.  ,  0.  , 59.  ],
        ...,
        [ 2.  ,  3.04,  2.08, ...,  0.  ,  0.  , 52.  ],
        [ 2.  ,  1.96,  1.68, ...,  1.  ,  0.  , 79.  ],
        [ 2.  ,  4.72,  3.56, ...,  1.  ,  0.  , 51.  ]]),
 array([0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0.,

3. 구조 결정(모델 만들기)

In [6]:
model = Sequential()
# input 피쳐가 16개이므로 input 차원은 16
model.add(Dense(30, input_dim = 16, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                510       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


4. 모델실행

In [7]:
model.compile(loss='binary_crossentropy', optimizer ='adam', metrics=['accuracy'])
history = model.fit(X, y, epochs=5, batch_size=6)

Epoch 1/5
79/79 [==============================] - 3s 3ms/step - loss: 0.5723 - accuracy: 0.8000
Epoch 2/5
79/79 [==============================] - 0s 3ms/step - loss: 0.4817 - accuracy: 0.8511
Epoch 3/5
79/79 [==============================] - 0s 2ms/step - loss: 0.4786 - accuracy: 0.8511
Epoch 4/5
79/79 [==============================] - 0s 3ms/step - loss: 0.4511 - accuracy: 0.8511
Epoch 5/5
79/79 [==============================] - 0s 3ms/step - loss: 0.4419 - accuracy: 0.8511


In [ ]:
model.evaluate()